from .event_routes import event_bp
from .sport_routes import sport_bp
from .team_routes import team_bp
from .game_routes import game_bp
from .game_score_routes import game_score_bp
from .criteria_routes import criteria_bp
from .judge_routes import judge_bp
from .score_component_routes import score_component_bp
from .event_sport_routes import event_sport_bp
from .report_routes import report_bp