"""judge scoring logic

Revision ID: cc4da31d5acd
Revises: 
Create Date: 2026-05-22 03:26:02.967221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4da31d5acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('start_day', sa.Date(), nullable=False),
    sa.Column('end_day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('scoring_types',
    sa.Column('scoring_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scoring_type_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('judges',
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('judge_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('judge_id'),
    sa.UniqueConstraint('event_id', 'judge_name', name='uq_event_judge_name')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('scoring_type_id', sa.Integer(), nullable=False),
    sa.Column('sport_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['scoring_type_id'], ['scoring_types.scoring_type_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=False),
    sa.Column('team_color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('event_id', 'team_name', name='uq_event_team_name')
    )
    op.create_table('event_sports',
    sa.Column('event_sport_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('schedule', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_sport_id'),
    sa.UniqueConstraint('event_id', 'sport_id', name='uq_event_sport')
    )
    op.create_table('criteria',
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('event_sport_id', sa.Integer(), nullable=False),
    sa.Column('criteria_name', sa.String(length=150), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_sport_id'], ['event_sports.event_sport_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('criteria_id'),
    sa.UniqueConstraint('event_sport_id', 'criteria_name', name='uq_event_sport_criteria')
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_sport_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('venue_name', sa.String(length=150), nullable=True),
    sa.Column('game_status', sa.String(length=50), nullable=False),
    sa.Column('round', sa.String(length=100), nullable=True),
    sa.Column('set_count', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_sport_id'], ['event_sports.event_sport_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_scores',
    sa.Column('game_score_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('set_scores', sa.JSON(), nullable=True),
    sa.Column('sets_won', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_score_id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_game_team')
    )
    op.create_table('score_components',
    sa.Column('score_component_id', sa.Integer(), nullable=False),
    sa.Column('game_score_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.criteria_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_score_id'], ['game_scores.game_score_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.judge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_component_id'),
    sa.UniqueConstraint('game_score_id', 'criteria_id', 'judge_id', name='uq_score_component')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_components')
    op.drop_table('game_scores')
    op.drop_table('games')
    op.drop_table('criteria')
    op.drop_table('event_sports')
    op.drop_table('teams')
    op.drop_table('sports')
    op.drop_table('judges')
    op.drop_table('scoring_types')
    op.drop_table('events')
    # ### end Alembic commands ###
